name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda install --file requirements.txt
    - name: Run tests
      shell: bash -el {0}
      run: |
        pytest -v