name: Build and Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    
    # Test the source code directly
    - name: Install test dependencies
      shell: bash -el {0}
      run: |
        conda install --file requirements.txt
    - name: Run direct tests
      shell: bash -el {0}
      run: |
        pytest -v tests/
    
    # Test pip package
    - name: Build pip package
      shell: bash -el {0}
      run: |
        pip install build
        python -m build
    - name: Test pip package
      shell: bash -el {0}
      run: |
        pip install dist/*.whl[test]
        cd tests
        pytest -v
        cd ..
    
    # Test conda package
    - name: Install conda-build
      shell: bash -el {0}
      run: |
        conda install conda-build
    - name: Build conda package
      shell: bash -el {0}
      run: |
        conda build conda.recipe
    - name: Install and test conda package
      shell: bash -el {0}
      run: |
        conda install -c ${CONDA_PREFIX}/conda-bld/ proxy-tester pytest requests psutil
        cd tests
        pytest -v